# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install the dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 5000

# Set environment variable for Flask
ENV FLASK_ENV=development

# Define the command to run the application with hot reload
CMD ["flask", "run", "--host=0.0.0.0"]