info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This microservice is responsible for managing tweets.
    It allows you to create and readtweets as well as retweet.
  version: 0.0.1
tags:
  - name: tweet
    description: Everything about the tweets
paths: