openapi: 3.0.3
info:
  title: Swagger Tweet 
  description: |-
    This microservice is responsible for managing tweets.
    It allows you to create and readtweets as well as retweet.
  version: 0.0.1
tags:
  - name: tweet
    description: Everything about the tweets
paths:
  /retweet/{tweetId}:
    post:
      tags:
        - tweet
      summary: Retweet a tweet
      description: Retweet a tweet
      operationId: retweetTweet
      parameters:
        - name: tweetId
          in: path
          description: ID of tweet to retweet
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tweet retweeted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tweet retweeted
        '400':
          description: Invalid tweet ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid tweet ID
        '404':
          description: Tweet not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tweet not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
  /info:
    get:
      tags:
        - tweet
      summary: Get microservice information
      description: Retrieve information about the microservice
      operationId: getMicroserviceInfo
      responses:
        '200':
          description: Microservice information retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Swagger Tweet
                  build:
                    type: string
                    example: 1.0.0
                  version:
                    type: string
                    example: 0.0.1
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error