version: "3.9"

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: polytex
    networks:
      authentification_network:
        ipv4_address: 192.168.1.2

  mysql:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      authentification_network:
        ipv4_address: 192.168.1.3

volumes:
  mysql-data:

networks:
  authentification_network:
    ipam:
      config:
        - subnet: 192.168.1.0/29